import { z } from 'zod';

export const medicalRecordSchema = z.object({
  id: z.string().optional(),
  numeroDossier: z.string().regex(/^[a-zA-Z0-9]{3}\/[a-zA-Z0-9]{2}$/, "Format requis: XXX/XX (ex: 123/24)"),
  nom: z.string().min(1, "Le nom est requis"),
  prenoms: z.string().min(1, "Les prénoms sont requis"),
  sexe: z.string().default('NP'),
  ddn: z.string().default(''),
  adresse: z.string().default(''),
  atcdFamCdt: z.string().default('NP'),
  atcdFamCancer: z.string().default('NP'),
  atcdPersCancer: z.string().default('NP'),
  ageDgc: z.number().default(0),
  cdt: z.string().default('NP'),
  variante: z.string().default('NP'),
  sizeSup2cm: z.string().default('NP'),
  ec: z.string().default('NP'),
  macroMicro: z.string().default('NP'),
  ev: z.string().default('NP'),
  mitoses: z.string().default('NP'),
  hgie: z.string().default('NP'),
  nse: z.string().default('NP'),
  filetNerv: z.string().default('NP'),
  r: z.string().default('NP'),
  t: z.string().default('NP'),
  n: z.string().default('NP'),
  m: z.string().default('NP'),
  chir: z.string().default('NP'),
  cg: z.string().default(''),
  tps: z.string().default(''),
  dgcI1: z.number().default(0),
  chirI1: z.number().default(0),
  nbreCures: z.number().default(0),
  actCum: z.number().default(0),
  suivi: z.number().default(0),
  rep2ans: z.string().default('NP'),
  rep5ans: z.string().default('NP'),
  rep10ans: z.string().default('NP'),
  dcd: z.string().default('NP'),
  dcdAge: z.number().default(0),
});

export type MedicalRecordFormValues = z.infer<typeof medicalRecordSchema>;
